### ISSUE TITLE
代理改进的想法

### ISSUE THREAD

**Issue by s1g0day** [etn0tw/WebBatchRequest#3]
正常情况下，我们需要区分网站是否存活分两种
1、不挂代理，测试国内连通性。
2、挂代理，测试国外连通性

那能不能在配置代理后自动检测所有可能，既
1、不挂代理，仅测试国内连通性。
2、挂代理，同时测试国内国外连通性，或者在通过代理测试连接失败的情况下测试国内连通性

优点:避免同样的任务跑两次
缺点:如果仅测试存活，可以考虑这么干。若在后期在添加扫描功能的话，确实不建议这么搞，但那就属于复合型工具

ps: 目前好像没用过类似功能的工具，师傅能否搞个这样的功能

**Comment by s1g0day** [comment]
由此可以给工具添加一个选项，也就是
1、国内检测
2、配置代理国外检测
3、同时检测

**Comment by etn0tw** [comment]
> 正常情况下，我们需要区分网站是否存活分两种 1、不挂代理，测试国内连通性。 2、挂代理，测试国外连通性
> 
> 那能不能在配置代理后自动检测所有可能，既 1、不挂代理，仅测试国内连通性。 2、挂代理，同时测试国内国外连通性，或者在通过代理测试连接失败的情况下测试国内连通性
> 
> 优点:避免同样的任务跑两次 缺点:如果仅测试存活，可以考虑这么干。若在后期在添加扫描功能的话，确实不建议这么搞，但那就属于复合型工具
> 
> ps: 目前好像没用过类似功能的工具，师傅能否搞个这样的功能

这个需求 利用率比较低，而且添加这个功能后 ui展示需要改变。你的优点中“避免跑两次”，但是流量层面 没什么不同还是两倍的流量，反而我觉得开两个界面也不是很麻烦。

**Comment by s1g0day** [comment]
感谢师傅的答复，其中有几点我做一些解释

1、添加这个功能后ui确实做出了一些改变，这点倒是可以动“添加代理设置”的UI，添加一个[选项]来决定是否同时检测。
2、我说的“避免跑两次”，不是指流量层面，仅仅是使用方面的。也就是不想频繁的开两个界面。数量低于300还好，如果是1000、2000等，就会变得麻烦。两个结果我需要合并去重，从而剔除相同的部分，也将其中差异部分合并到一起。如果同时检测的话，就可以减少这一个步骤(也许就是几秒钟的功夫)。就实际工作中，有时会因繁琐的步骤造成烦躁进而影响状态，尤其是任务量大需要分批处理的时候。
3、利用率低这个问题，我想大多数人都愿意仅开一个界面就完成相应的任务。

当然，这个需求仅仅是突发奇想，属于特色功能，是否采纳还有待商榷。
